import SmallYardProject from '@/components/small-yard-project';
import PlantedRoofProject from '@/components/planted-roof-project';
import TransitToTrailsProject from '@/components/transit-to-trails-project';
import BellsPondProject from '@/components/bells-pond-project';

import {watermarkedPlan} from "@/lib/plan-watermarks";
import ConservationPlanningProject from '@/components/conservation-planning-project';
import StudyExperience from '@/components/study-experience';
import {studyNarratives} from '@/lib/study-narratives';
import {notFound} from 'next/navigation';import {projects} from '@/lib/projects';import {Header,Footer} from '@/components/shell';import ProjectExperience from '@/components/project-experience';import {projectDetails} from '@/lib/project-details';import Motion from '@/components/motion';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(x=>x.slug===slug);return {title:p?.title||'Project',description:p?.summary};}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=projects.find(x=>x.slug===slug);if(!p)notFound();if(p.slug==='small-yard-renovation')return <SmallYardProject project={p}/>;if(p.slug==='planted-roofs')return <PlantedRoofProject project={p}/>;if(p.slug==='transit-to-trails')return <TransitToTrailsProject/>;if(p.slug==='bells-pond')return <BellsPondProject/>;if(p.planning)return <ConservationPlanningProject/>;const next=projects[(projects.indexOf(p)+1)%projects.length];if(p.study)return <main id="top"><Header/><StudyExperience project={p} details={projectDetails[p.slug]} narrative={studyNarratives[p.slug]}/><a className="next-project" href={watermarkedPlan('/projects/'+next.slug)}><img src={watermarkedPlan(next.hero)} alt="" loading="lazy"/><div><p className="eyebrow">CONTINUE EXPLORING</p><h2>{next.title} ↗</h2></div></a><Footer/></main>;return <main id="top"><Motion/><section className="hero project-hero"><img className="hero-image" src={watermarkedPlan(p.hero)} alt={p.title+' landscape'}/><Header/><div className="hero-copy"><a className="eyebrow" href={watermarkedPlan("/projects")}>← ALL PROJECTS</a><h1>{p.title}</h1><p>{p.category}</p></div><div className="hero-bottom"><p>{p.location}</p><a href={watermarkedPlan("#details")}>DESIGN DETAILS ↗</a><a href={watermarkedPlan("#photographs")}>EXPLORE {p.images.length}{' '}{p.study?'SOURCE VIEWS':'PHOTOGRAPHS'} ↓</a></div></section><ProjectExperience project={p} details={projectDetails[p.slug]}/>{p.study&&<section className="study-built-link"><div><p className="eyebrow">RELATED BUILT-WORK PHOTOGRAPHY</p><h2>Explore these ideas<br/><em>in another landscape.</em></h2><p>Stone paths, layered planting, and water in the supplied Morningside photographs. A separate project with its own site conditions and story.</p><a className="line-link" href={watermarkedPlan("/projects/137-summer")}>Visit Morningside ↗</a></div><a href={watermarkedPlan("/projects/137-summer")}><img src={watermarkedPlan("/images/summer-24.webp")} alt="Stone steps and planting at Morningside, a separate project" loading="lazy"/></a></section>}<a className="next-project" href={watermarkedPlan('/projects/'+next.slug)}><img src={watermarkedPlan(next.hero)} alt="" loading="lazy"/><div><p className="eyebrow">CONTINUE EXPLORING</p><h2>{next.title} ↗</h2></div></a><Footer/></main>}

export function generateStaticParams(){return projects.map(p=>({slug:p.slug}));}
