
import {watermarkedPlan} from "@/lib/plan-watermarks";
import StructuresGallery from '@/components/structures-gallery';
import SurveyPhoto from '@/components/survey-photo';
import Image from 'next/image';
import PlantedRoofGallery from '@/components/planted-roof-gallery';
import StudyConnections from '@/components/study-connections';
import {notFound} from 'next/navigation';import {Header,Footer} from '@/components/shell';import {services} from '@/lib/services';import {projects} from '@/lib/projects';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const s=services.find(x=>x.slug===slug);return{title:s?.title||'Landscape Design',description:s?.intro}}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const s=services.find(x=>x.slug===slug);if(!s)notFound();const project=projects.find(p=>p.slug===s.related);return <main id="top"><Header/><section className="service-lead"><div><a className="eyebrow" href={watermarkedPlan("/landscape-design")}>← LANDSCAPE DESIGN</a><h1>{s.title}</h1><p>{s.subtitle}</p></div>{s.slug==='lighting'?<figure className="lighting-plan-feature"><a href={watermarkedPlan(s.image)} target="_blank" rel="noreferrer"><img src={watermarkedPlan(s.image)} alt={s.imageAlt}/><span className="line-link">Enlarge the lighting plan ↗</span></a><figcaption>Morningside · North-side lighting plan update · May 2025</figcaption></figure>:<img src={watermarkedPlan(s.image.startsWith('/')?s.image:`/images/summer-${s.image}.webp`)} alt={s.imageAlt||s.title+' — landscape context'}/>}</section>{s.slug==='lighting'&&<section className="lighting-photo-gallery" aria-label="Installed landscape lighting"><figure><img src="/images/summer-3.webp" alt="Installed path lights beside planted stone steps at Morningside" loading="lazy"/><figcaption>Path lights placed along the stone steps, among the planting.</figcaption></figure><figure><img src="/images/summer-80.webp" alt="A low path light beside stone steppers at the pool terrace" loading="lazy"/><figcaption>Low fixtures along the pool terrace’s stone steppers. Installed lighting photographed in daylight.</figcaption></figure></section>}<section className="service-body"><div className="service-body-intro"><p>{s.intro}</p>{s.slug==='site-analysis'&&<SurveyPhoto/>}{s.slug==='lighting'&&<a className="line-link" href="https://darksky.org/resources/guides-and-how-tos/lighting-principles/" target="_blank" rel="noreferrer">DarkSky’s five lighting principles ↗</a>}{s.note&&<p className="professional-note">{s.note}</p>}</div><div className="service-topics">{s.sections.map((section,i)=><article key={section.title}><span className="eyebrow">{String(i+1).padStart(2,'0')}</span><h2>{section.title}</h2><p>{section.text}</p>{section.items&&<ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul>}{section.photo&&<figure className="service-topic-photo"><Image src={watermarkedPlan(section.photo.src)} alt={section.photo.alt} width={section.photo.width} height={section.photo.height} unoptimized loading="lazy"/><figcaption>{section.photo.caption}</figcaption></figure>}</article>)}</div></section>{s.slug==='structures'&&<StructuresGallery/>}{project&&<a className="next-project" href={watermarkedPlan('/projects/'+project.slug+'#details')}><img src={watermarkedPlan(project.hero)} alt={project.title} loading="lazy"/><div><p className="eyebrow">EXPLORE THE DESIGN DETAILS</p><h2>{project.title} ↗</h2></div></a>}{s.slug==='planted-roofs'&&<PlantedRoofGallery/>}<StudyConnections context={s.slug}/><Footer/></main>}

export function generateStaticParams(){return services.map(p=>({slug:p.slug}));}
