import StructuresGallery from '@/components/structures-gallery';
import SurveyPhoto from '@/components/survey-photo';
import Image from 'next/image';
import PlantedRoofGallery from '@/components/planted-roof-gallery';
import StudyConnections from '@/components/study-connections';
import {notFound} from 'next/navigation';import {Header,Footer} from '@/components/shell';import {services} from '@/lib/services';import {projects} from '@/lib/projects';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const s=services.find(x=>x.slug===slug);return{title:s?.title||'Landscape Design',description:s?.intro}}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const s=services.find(x=>x.slug===slug);if(!s)notFound();const project=projects.find(p=>p.slug===s.related);return <main id="top"><Header/><section className="service-lead"><div><a className="eyebrow" href="/landscape-design">← LANDSCAPE DESIGN</a><h1>{s.title}</h1><p>{s.subtitle}</p></div><img src={s.image.startsWith('/')?s.image:`/images/summer-${s.image}.webp`} alt={s.imageAlt||s.title+' — landscape context'}/></section><section className="service-body"><div className="service-body-intro"><p>{s.intro}</p>{s.slug==='site-analysis'&&<SurveyPhoto/>}{s.note&&<p className="professional-note">{s.note}</p>}</div><div className="service-topics">{s.sections.map((section,i)=><article key={section.title}><span className="eyebrow">{String(i+1).padStart(2,'0')}</span><h2>{section.title}</h2><p>{section.text}</p>{section.items&&<ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul>}{section.photo&&<figure className="service-topic-photo"><Image src={section.photo.src} alt={section.photo.alt} width={section.photo.width} height={section.photo.height} unoptimized loading="lazy"/><figcaption>{section.photo.caption}</figcaption></figure>}</article>)}</div></section>{s.slug==='structures'&&<StructuresGallery/>}{project&&<a className="next-project" href={'/projects/'+project.slug+'#details'}><img src={project.hero} alt={project.title} loading="lazy"/><div><p className="eyebrow">EXPLORE THE DESIGN DETAILS</p><h2>{project.title} ↗</h2></div></a>}{s.slug==='planted-roofs'&&<PlantedRoofGallery/>}<StudyConnections context={s.slug}/><Footer/></main>}

export function generateStaticParams(){return services.map(p=>({slug:p.slug}));}
