'use client';
import {useState} from 'react';
import {watermarkedPlan} from '@/lib/plan-watermarks';
const features=[
 {title:'Public arrival',x:60,y:39,category:'ARRIVAL + COMMUNITY',text:'Shaded parking, restrooms, natural play, and a pavilion create a welcoming starting point for the trail network. The proposal connects practical amenities with opportunities to gather and learn.',skill:'Site planning · Circulation · Shared outdoor space'},
 {title:'Bridge + observation deck',x:43.5,y:25,category:'TRAIL + STRUCTURE DESIGN',text:'A bridge spans the swale among existing old oaks. Seating and space for mobility devices make the crossing a place to pause, while concentrating activity along a defined route.',skill:'Spatial sketching · Trail design · Sensitive site response',image:'/studies/bells-pond/bridge.webp'},
 {title:'Bird blind + boardwalk',x:29,y:47,category:'HABITAT + HUMAN EXPERIENCE',text:'A proposed blind near the western floodplain offers views into the forest. Boardwalk connections guide visitors across wet ground while keeping activity focused along designated routes.',skill:'Habitat awareness · Low-impact access · Wildlife observation'},
 {title:'Meadow + water station',x:52,y:67,category:'LANDSCAPE EXPERIENCE',text:'A gazebo and drinking fountain use the existing well as a destination along the sunny meadow route. Selective mowing retains meadow and shrubland, creating varied habitat and changing views.',skill:'Plant-community planning · Rest points · Stewardship'},
 {title:'Perched bird blind',x:36,y:85,category:'DESIGNING WITH TOPOGRAPHY',text:'A boardwalk extends from the southern slope to an elevated observation space overlooking the creek and floodplain canopy. The sketch explores a treehouse-like experience within the existing landscape.',skill:'Sectional thinking · Structure design · Framed views',image:'/images/structures/birds-observation.webp'},
 {title:'Housing + planted edges',x:74,y:45,category:'CONSERVATION + HOUSING',text:'Housing is located near existing infrastructure. Native hedgerows and layered planting define private and shared areas, while trails connect the neighborhoods to the conservation landscape.',skill:'Land-use planning · Vegetative screening · Connected landscapes'}
];
export default function BellsPondMap(){const [selected,setSelected]=useState(0);const active=features[selected];return <section id="explore-plan" className="study-plan bells-interactive-map"><div className="authored-section-head"><p className="eyebrow">EXPLORE THE DESIGN</p><h2>One landscape.<br/><em>Connected experiences.</em></h2><p>Select a numbered place or a topic to see the design intention.</p></div><p className="bells-map-credit">Overall plan drawn by Anna Goff, CSLD ’26 · Collaborative project with Zaviere Drumm</p><div className="plan-explorer"><div><div className="hotspot-map"><img src={watermarkedPlan('/studies/bells-pond/plan.webp')} alt="Bell’s Pond concept plan with selectable design locations" loading="lazy"/>{features.map((f,i)=><button type="button" key={f.title} style={{left:f.x+'%',top:f.y+'%'}} className={selected===i?'active':''} aria-label={f.title} aria-pressed={selected===i} aria-controls="bells-map-detail" onClick={()=>setSelected(i)}>{String(i+1).padStart(2,'0')}</button>)}</div><a className="line-link" href={watermarkedPlan('/studies/bells-pond/plan.webp')} target="_blank" rel="noreferrer">Open large plan ↗</a></div><div className="feature-reader"><div className="feature-index" role="group" aria-label="Design locations">{features.map((f,i)=><button type="button" key={f.title} aria-pressed={selected===i} aria-controls="bells-map-detail" onClick={()=>setSelected(i)}>{String(i+1).padStart(2,'0')} {f.title}</button>)}</div><article id="bells-map-detail" aria-live="polite"><p className="eyebrow">{active.category}</p><h3>{active.title}</h3><p>{active.text}</p><p className="bells-map-skills">{active.skill}</p>{active.image&&<figure><a href={watermarkedPlan(active.image)} target="_blank" rel="noreferrer"><img src={watermarkedPlan(active.image)} alt={active.title+' concept sketch'} /></a><figcaption>Drawn by Zaviere Drumm</figcaption></figure>}</article></div></div><p className="bells-map-note">Concept design · Selected highlights from Finding Common Ground, The Conway School, Spring 2026.</p></section>}
