import {Header,Footer} from '@/components/shell';
import {watermarkedPlan} from '@/lib/plan-watermarks';
const plan='/studies/bells-pond/plan.webp';
const sketches=[
{image:'/studies/bells-pond/vegetation.webp',label:'01 / SITE ANALYSIS',title:'Read the landscape before drawing the plan.',text:'Mapping existing vegetation reveals the relationship between returning woodland, open fields, wetlands, and disturbed ground. These patterns guide where restoration and access can work together.',credit:"Vegetation Analysis Drawn By Anna Goff, CSLD ’26"},
{image:'/studies/bells-pond/bridge.webp',label:'02 / TRAIL + STRUCTURE DESIGN',title:'A crossing becomes a place to pause.',text:'The bridge and observation deck sketch connects circulation with a closer experience of the creek. The concept explores structure, seating, and a focused crossing through sensitive ground.',credit:'Bridge and observation deck · Design proposal'},
{image:'/images/structures/birds-observation.webp',label:'03 / HABITAT + HUMAN EXPERIENCE',title:'A quieter way to encounter wildlife.',text:'An elevated approach and screened observation space give the trail a destination. The sketch studies how a small structure can frame views and concentrate visitor activity at the habitat edge.',credit:'Bird observation blind · Design proposal'}
];
export default function BellsPondProject(){return <main id="top"><Header/><section className="conservation-project-heading"><a className="eyebrow" href="/projects/">← ALL PROJECTS</a><p className="eyebrow">BELL’S POND CONSERVATION PROPERTY · SPRING 2026</p><h1>Finding<br/><em>common ground.</em></h1><p>A shared landscape plan for conservation, affordable housing, and public access in Greenport and Livingston, New York.</p><a className="line-link" href="#plan">Explore the plan ↓</a></section><figure id="plan" className="conservation-feature"><div className="plan-brand-header">Overall Plan Drawn by Anna Goff, CSLD ’26</div><a href={watermarkedPlan(plan)} target="_blank" rel="noreferrer"><img src={watermarkedPlan(plan)} alt="Bell’s Pond overall landscape plan connecting conservation land, housing areas, and trails"/><span className="line-link">Enlarge the overall plan ↗</span></a><figcaption>Finding Common Ground · Anna Goff & Zaviere Drumm · The Conway School, Spring 2026 · Collaborative design study</figcaption></figure><section id="details" className="conservation-project-brief"><p className="eyebrow">143 ACRES / ONE CONNECTED LANDSCAPE</p><h2>Bring different needs<br/><em>into a shared plan.</em></h2><p>The study brings together the goals of Columbia Land Conservancy, Columbia-Greene Habitat for Humanity, and Trillium Community Land Trust. Housing is considered alongside existing infrastructure, habitat, and water, while trails connect people with the conservation landscape.</p><p>Site analysis, land-use planning, ecological restoration, and spatial sketching turn those relationships into a clear design direction.</p></section><div className="conservation-design-details">{sketches.map(s=><section key={s.image}><figure><a href={watermarkedPlan(s.image)} target="_blank" rel="noreferrer"><img src={watermarkedPlan(s.image)} alt={s.title+' Design sketch.'} loading="lazy"/></a><figcaption>{s.credit}</figcaption></figure><div><p className="eyebrow">{s.label}</p><h2>{s.title}</h2><p>{s.text}</p></div></section>)}</div><section className="conservation-support"><div><p className="eyebrow">FROM SITE READING TO DESIGN</p><h2>Ecology, access, and form.</h2><p>The selected work shows how analysis can shape an overall plan, and how focused sketches can test the details that make a landscape useful and memorable.</p></div><a className="line-link" href="/projects/">Explore more projects ↗</a></section><Footer/></main>}
