import {watermarkedPlan} from '@/lib/plan-watermarks';
import {Header,Footer} from '@/components/shell';
import ConservationConceptMap from '@/components/conservation-concept-map';
const details=[
 {image:'concept-meadow',label:'01 / MEADOW + ORCHARD',title:'An open landscape with a living edge.',text:'A managed meadow and native orchard hold the open ground beside the house. Curving paths connect the planting while legacy oaks and sugar maples remain part of the landscape.'},
 {image:'concept-buffer',label:'02 / WOODLAND BUFFER',title:'Planting that follows the slope.',text:'A layered buffer wraps the eastern edge of the proposed house, connecting north-slope planting with the woodland below. Trees, shrubs, and groundcover bring structure to the transition.'},
 {image:'concept-entry',label:'03 / ARRIVAL + WATER',title:'Make the entry part of the ecology.',text:'The concept brings the permeable driveway, preserved trees, and entryway wetland into one arrival sequence. Planting gives the approach a softer edge and connects it to the wider conservation plan.'}
];
export default function ConservationPlanningProject(){return <main id="top"><Header/><section className="conservation-project-heading"><a className="eyebrow" href="/projects/">← ALL PROJECTS</a><p className="eyebrow">CONSERVATION PLANNING · DESIGN CONCEPT</p><h1>A landscape connected<br/><em>by soil, water, and habitat.</em></h1><p>Woodland buffers, a meadow orchard, and a wetland entry shape the landscape around a proposed home.</p><a className="line-link" href="#plan">Explore the concept ↓</a></section><ConservationConceptMap/><section className="conservation-project-brief"><p className="eyebrow">THE DESIGN</p><h2>Protect what is here.<br/><em>Connect what comes next.</em></h2><p>The plan works with the site’s contours and existing trees to bring daily use and conservation together. Open meadow, layered planting, and wet ground each have a place in the overall design.</p></section><div className="conservation-design-details">{details.map(d=><section key={d.image}><img src={watermarkedPlan(`/conservation-planning/${d.image}.webp`)} alt={d.title+' Enlarged concept plan detail.'} loading="lazy"/><div><p className="eyebrow">{d.label}</p><h2>{d.title}</h2><p>{d.text}</p></div></section>)}</div><section id="report" className="conservation-support"><div><p className="eyebrow">BEHIND THE DESIGN</p><h2>The supporting planting strategy.</h2><p>The companion report develops the buffer, slope, wetland, and meadow planting palettes in more detail.</p></div><a className="line-link" href="/conservation-planning/conservation-planning-report.pdf" target="_blank" rel="noreferrer">View the concept report ↗</a></section><Footer/></main>}
