'use client';
import {useState} from 'react';
import {watermarkedPlan} from '@/lib/plan-watermarks';
const areas=[
{title:'Meadow + native orchard',x:28,y:57,text:'Managed meadow and a native orchard hold the open ground beside the home. Curving paths connect these habitats while legacy trees remain part of the landscape.',image:'concept-meadow'},
{title:'Courtyard planting',x:55,y:31,text:'Planting around the courtyard brings a garden close to daily life, connecting the proposed home with the larger landscape.',image:'concept-buffer'},
{title:'Woodland buffer',x:64,y:46,text:'Layers of trees, shrubs, and groundcover follow the slope along the eastern edge, connecting the garden with existing woodland.',image:'concept-buffer'},
{title:'Permeable driveway',x:49,y:56,text:'The proposed permeable driveway forms the arrival route. Its layout connects the home, preserved trees, and planted edges.',image:'concept-entry'},
{title:'Entryway wetland',x:48,y:84,text:'Wetland planting shapes the entry, responding to wet ground and making water part of the landscape experience.',image:'concept-entry'},
{title:'North-slope planting',x:43,y:13,text:'Planting follows the contours above the house, linking the north slope to the eastern buffer and the site’s broader habitat structure.',image:'concept-buffer'}
];
export default function ConservationConceptMap(){const [selected,setSelected]=useState(0);const active=areas[selected];return <section id="plan" className="conservation-feature conservation-concept-map"><p className="eyebrow">EXPLORE THE CONCEPT / SELECT A NUMBERED AREA</p><div className="hotspot-map"><img src={watermarkedPlan('/conservation-planning/concept-overview.webp')} alt="Conservation concept plan with selectable planting and arrival areas"/>{areas.map((a,i)=><button key={a.title} type="button" className={selected===i?'active':''} style={{left:a.x+'%',top:a.y+'%'}} aria-label={a.title} aria-pressed={selected===i} aria-controls="conservation-map-detail" onClick={()=>setSelected(i)}>{String(i+1).padStart(2,'0')}</button>)}</div><a className="line-link" href={watermarkedPlan('/conservation-planning/concept-overview.webp')} target="_blank" rel="noreferrer">Enlarge the concept plan ↗</a><div className="feature-reader"><div className="feature-index" role="group" aria-label="Concept plan areas">{areas.map((a,i)=><button key={a.title} aria-pressed={selected===i} aria-controls="conservation-map-detail" onClick={()=>setSelected(i)}>{String(i+1).padStart(2,'0')} {a.title}</button>)}</div><article id="conservation-map-detail" aria-live="polite"><h3>{active.title}</h3><p>{active.text}</p><a href={(selected===5?'/watermarked-plans/conservation-north-slope.svg':watermarkedPlan('/conservation-planning/'+active.image+'.webp'))} target="_blank" rel="noreferrer"><img src={(selected===5?'/watermarked-plans/conservation-north-slope.svg':watermarkedPlan('/conservation-planning/'+active.image+'.webp'))} alt={active.title+' enlarged plan detail'}/><span className="line-link">View detail ↗</span></a></article></div></section>}
