'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const books:Record<string,{image:number;caption:string}[]>={
 'Reclaimed granite':[{image:81,caption:'Broad granite slabs frame the gathering terrace.'},{image:85,caption:'A feature stone contrasts with the cut paving at the pool’s edge.'},{image:35,caption:'The paved gathering space connects the pool and pool house.'},{image:160,caption:'An aerial view reveals the terrace within the wider stone and garden layout.'}],
 'Stone steppers':[{image:100,caption:'An informal stone path winds through the pond-side planting.'},{image:24,caption:'Stone steps climb through the garden beds.'},{image:58,caption:'Broad stone treads connect the garden’s changing levels.'},{image:21,caption:'Stepping stones cross the lawn toward the house.'}],
 'Native plants':[{image:32,caption:'Pink coneflowers bring color and texture to the summer garden.'},{image:34,caption:'Flowering plants and grasses form layers across the hillside.'},{image:115,caption:'Yellow summer flowers beside the pond.'},{image:113,caption:'The pond-side garden connects with the wooded landscape.'}],
 'Groundcovers':[{image:36,caption:'Low mats of planting fill the joints along the pool edge.'},{image:90,caption:'Low planting borders the garden path and steps.'},{image:80,caption:'Groundcovers weave between broad stones beside the water.'},{image:93,caption:'A view from above shows the transition from planted joints to lawn and garden beds.'}]
};
export default function MaterialLookbook({items}:{items:{name:string;role:string;note:string}[]}){
 const[active,setActive]=useState<string|null>(null);const[index,setIndex]=useState(0);const[start,setStart]=useState<number|null>(null);
 const photos=active?books[active]:[];
 const move=(delta:number)=>setIndex(i=>(i+delta+photos.length)%photos.length);
 useEffect(()=>{if(!active)return;const key=(e:KeyboardEvent)=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();setIndex(i=>(i+(e.key==='ArrowRight'?1:-1)+photos.length)%photos.length)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[active,photos.length]);
 return <><div className="palette-rows palette-lookbooks">{items.map((item,i)=><button className="material-lookbook-trigger" key={item.name} aria-label={`Open ${item.name} look-book`} onClick={()=>{setIndex(0);setActive(item.name)}}><span className="material-number">0{i+1}</span><span className="material-copy"><span className="eyebrow">{item.role}</span><span className="material-title">{item.name}</span><span className="material-note">{item.note}</span><span className="material-open">Explore look-book ↗</span></span></button>)}</div><Dialog open={active!==null} onOpenChange={v=>{if(!v)setActive(null)}}><DialogContent className="lightbox material-lookbook" showCloseButton={false}><div className="lightbox-top"><DialogTitle>{active} · Look-book</DialogTitle><button onClick={()=>setActive(null)} aria-label="Close look-book">Close ×</button></div><DialogDescription className="sr-only">Morningside material photographs. Use the arrow buttons or left and right arrow keys to browse. Escape closes the look-book.</DialogDescription><div className="lightbox-image" onTouchStart={e=>setStart(e.touches[0].clientX)} onTouchEnd={e=>{if(start!==null){const delta=e.changedTouches[0].clientX-start;if(Math.abs(delta)>50)move(delta<0?1:-1)}setStart(null)}}>{photos[index]&&<img src={`/images/summer-${photos[index].image}.webp`} alt={photos[index].caption}/>}</div><div className="lightbox-bottom"><button onClick={()=>move(-1)} aria-label="Previous photograph">←</button><p aria-live="polite">{index+1} / {photos.length} — {photos[index]?.caption}<span className="material-photo-credit">Photos by Nick Glimenakis</span></p><button onClick={()=>move(1)} aria-label="Next photograph">→</button></div></DialogContent></Dialog></>;
}
