'use client';
import {watermarkedPlan} from "@/lib/plan-watermarks";

import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const groups=[{name:'Morningside',id:'morningside',intro:'Entry planting, stonework, and routes through the landscape. These studies explore how arrival, views, and movement connect the house to its setting.',sheets:[['morningside-perspectives-1','Planting along the front stairs','Perspective study · April 2024'],['morningside-perspectives-2','The formal entry','Planting and hardscape study · April 2024'],['morningside-perspectives-3','A path across the north slope','Perspective study · April 2024'],['morningside-driveway-october-1','Refining the driveway','Revised driveway plan · October 2024']]},{name:'Stone Terrace Garden',id:'schupack-good',intro:'Photo-based sketches and plans bring the house, hillside, planting, and stone terraces into a shared composition.',sheets:[['schupack-perspectives-1','The house within the slope','SK1 · May 2026'],['schupack-perspectives-2','Steps into the garden','SK2 · May 2026'],['schupack-slope-1','Following the hillside','Slope perspective'],['schupack-site-plan-1','The wider site','Draft site plan'],['schupack-hardscape-1','A framework of stone','Annotated hardscape plan']]}];
const sketchImage=(name:string,thumb=false)=>`/watermarked-plans/${name}${thumb?'-thumb':''}-branded.svg`;
export default function SketchGallery(){
 const [selected,setSelected]=useState<string[]|null>(null);const [zoom,setZoom]=useState(100);
 return <><nav className="sketch-links" aria-label="Sketch projects">{groups.map(g=><a key={g.id} href={watermarkedPlan('#'+g.id)}>{g.name} ↓</a>)}</nav>{groups.map(g=><section key={g.id} id={g.id} className="sketch-group"><div className="section-title"><div><p className="eyebrow">DESIGN EXPLORATIONS</p><h2>{g.name}</h2></div><p>{g.intro}</p></div><div className="sketch-grid">{g.sheets.map(s=><button className={`sketch-card ${s[0]==='schupack-hardscape-1'?'sketch-card-portrait':''}`} key={s[0]} onClick={()=>{setSelected(s);setZoom(100)}}><div><img src={sketchImage(s[0],true)} alt={s[1]+' — '+g.name} loading="lazy"/><span>Explore drawing ↗</span></div><p className="eyebrow">{s[2]}</p><h3>{s[1]}</h3></button>)}</div></section>)}<p className="sketch-credit">Drawings supplied by Sweetfern Ecological Design. Original annotations and credits are retained. These drawings show design studies and proposals; they are not a record of completed construction.</p><Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="art-dialog" showCloseButton={false}><button className="art-close" onClick={()=>setSelected(null)}>Close ×</button><DialogTitle>{selected?.[1]}</DialogTitle><DialogDescription>{selected?.[2]} · Zoom to read the original drawing.</DialogDescription><div className="art-zoom-controls"><label htmlFor="sketch-zoom">Zoom {zoom}%</label><input id="sketch-zoom" type="range" min={100} max={300} step={25} value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><button onClick={()=>setZoom(100)}>Fit</button></div><div className="art-zoom-viewport">{selected&&<img src={sketchImage(selected[0])} alt={selected[1]} style={{width:zoom+'%',maxWidth:'none',height:'auto'}}/>}</div>{selected&&<a className="art-full-image" href={sketchImage(selected[0])} target="_blank" rel="noreferrer">Open full drawing ↗</a>}</DialogContent></Dialog></>;
}
