'use client';
import {watermarkedPlan} from "@/lib/plan-watermarks";

import {useState} from 'react';
import Image from 'next/image';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {structurePhotos,structureProposals} from '@/lib/structure-images';
export default function StructuresGallery(){
 const [selected,setSelected]=useState<(typeof structurePhotos)[number]|null>(null);
 return <section className="structures-gallery"><div className="section-title"><div><p className="eyebrow">STRUCTURES IN THE GARDEN</p><h2>Places to pause.<br/><em>Ways to connect.</em></h2></div></div><div className="structure-photo-grid">{structurePhotos.map(p=><figure key={p.src}><button onClick={()=>setSelected(p)} aria-label={'Enlarge '+p.title}><Image src={watermarkedPlan(p.src)} alt={p.alt} width={p.width} height={p.height} unoptimized loading="lazy"/><span>↗</span></button><figcaption><h3>{p.title}</h3><p>{p.alt}</p></figcaption></figure>)}</div><div className="structure-study-heading"><p className="eyebrow">BELL’S POND CONSERVATION PROPERTY · DESIGN PROPOSALS</p><h2>Access, observation,<br/><em>and habitat.</em></h2><p>Bridge and bird-blind concepts from the collaborative Finding Common Ground plan set. Anna Goff &amp; Zaviere Drumm · The Conway School · Spring 2026.</p></div><div className="structure-photo-grid structure-proposal-grid">{structureProposals.map(p=><figure key={p.src}><button onClick={()=>setSelected(p)} aria-label={'Enlarge '+p.title}><Image src={watermarkedPlan(p.src)} alt={p.alt+' Proposed design illustration.'} width={p.width} height={p.height} unoptimized loading="lazy"/><span>↗</span></button><figcaption><p className="eyebrow">PROPOSED DESIGN</p><h3>{p.title}</h3><p>{p.alt}</p></figcaption></figure>)}</div><a className="line-link" href={watermarkedPlan("/projects/bells-pond/")}>Explore Bell’s Pond Conservation Property ↗</a><Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="roof-photo-dialog"><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?.alt}{selected&&structureProposals.some(p=>p.src===selected.src)?' Proposed design · Anna Goff & Zaviere Drumm · The Conway School · Spring 2026.':''}</DialogDescription>{selected&&<Image src={watermarkedPlan(selected.src)} alt={selected.alt} width={selected.width} height={selected.height} unoptimized/>}</DialogContent></Dialog></section>;
}
