'use client';
import {watermarkedPlan} from "@/lib/plan-watermarks";

import {useState,useEffect} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import type {Project} from '@/lib/projects';
import type {ProjectDetails} from '@/lib/project-details';
import type {StudyNarrative} from '@/lib/study-narratives';
const bellsAnalysisTitles:Record<string,string>={Vegetation:'Vegetation Analysis by Anna Goff',Soils:'Soil Analysis by Zaviere Drumm','Water + slopes':'Hydrology Analysis by Anna Goff','Habitat + access':'Vegetation Analysis by Anna Goff'};
const sandplanCommunityImages=[['rain-garden-reference','Iris flowering at the water’s edge'],['entry-reference','Layered coneflowers and perennial planting'],['front-meadow-reference','Flowering coneflowers in a meadow planting'],['screen-reference','Evergreen foliage for a planted screen'],['south-yard-reference','Pine canopy and open understory'],['sandplain-reference','Dry meadow grasses at a woodland edge']];
const bellsCommunityImages=[['meadow-reference','Flowering asters in a meadow'],['shrubland-reference','Sumac fruit and layered foliage'],['upland-reference','Maple canopy in autumn'],['before-creek','Existing creekside vegetation at Bell’s Pond'],['neighborhood','Residential planting and shared greenspace design illustration']];
export default function StudyExperience({project:p,details,narrative:n}:{project:Project;details:ProjectDetails;narrative:StudyNarrative}){
const[zoomLevel,setZoomLevel]=useState(100);const[shown,setShown]=useState(12);const[feature,setFeature]=useState(0);const[community,setCommunity]=useState('All');const[query,setQuery]=useState('');const[zoom,setZoom]=useState<{src:string;title:string}|null>(null);const[archive,setArchive]=useState(false);
useEffect(()=>{const hash=location.hash;if(hash==='#photographs'||hash==='#details')requestAnimationFrame(()=>document.getElementById(hash==='#details'?'read-the-land':'explore-plan')?.scrollIntoView({behavior:'instant'}));},[]);
useEffect(()=>setShown(12),[query,community]);
const communityImages=n.key==='sandplan'?sandplanCommunityImages:bellsCommunityImages;const active=n.features[feature];const plants=n.plants.filter(x=>(community==='All'||x.community===community)&&`${x.name} ${x.latin} ${x.role}`.toLowerCase().replaceAll(/\s/g,'').includes(query.toLowerCase().replaceAll(/\s/g,'')));
const picture=(src:string,title:string)=>{setZoomLevel(100);setZoom({src,title});};
return <div className={`authored-study ${n.key}`}>
<section className="authored-lead"><div><a className="eyebrow" href={watermarkedPlan("/projects")}>← ALL PROJECTS</a><p className="eyebrow study-kicker">{n.kicker}</p><h1>{n.title}</h1><p className="authored-deck">{n.subtitle}</p><a className="line-link" href={watermarkedPlan("#explore-plan")}>Explore the landscape ↓</a></div><button className="lead-art" onClick={()=>picture(n.hero,n.title)} aria-label="Enlarge project illustration"><img src={watermarkedPlan(n.hero)} alt={n.heroAlt}/><span>DESIGN ILLUSTRATION ↗</span></button></section>
<div className="authored-byline"><span>{p.location}</span><span>{p.credit?.split(' · ').slice(0,-1).join(' · ')}</span><span>{n.date} · Landscape design</span></div>
<nav className="study-chapter-nav" aria-label="Project chapters">{[['The brief','the-brief'],['Site analysis','read-the-land'],['Design choices','design-choices'],['Explore the plan','explore-plan'],[n.key==='sandplan'?'Living outdoors':'Neighborhood + trails','living-landscape'],['Planting','planting-communities'],['Stewardship','long-term-care']].map(([label,id],i)=><a key={id} href={watermarkedPlan('#'+id)}><span>0{i+1}</span>{label}</a>)}</nav>
<section id="the-brief" className="authored-intro"><div><p className="eyebrow">01 / THE BRIEF</p><h2>{n.briefTitle}</h2></div><div>{n.brief.map(t=><p key={t}>{t}</p>)}<ul className="authored-tags">{p.tags.map(t=><li key={t}>{t}</li>)}</ul></div><dl className="study-metrics">{n.metrics.map(m=><div key={m.label}><dt>{m.value}</dt><dd>{m.label}</dd></div>)}</dl></section><div className="study-photo-strip">{(n.key==='sandplan'?[['before-house','Existing home — single-level living and a home to age in place.'],['before-garden','The existing vegetable garden'],['before-meadow','Meadow beginnings']]:[['before-creek','Creekside vegetation'],['before-field','An existing route through the site'],['renovated-barn','The renovated barn']]).map(([file,caption])=><figure key={file}><img src={watermarkedPlan(`/studies/${n.key}/${file}.webp`)} alt={caption} loading="lazy"/><figcaption>{caption}</figcaption></figure>)}</div>
{n.partners&&<section className="study-partners"><p className="eyebrow">THREE MISSIONS / ONE LANDSCAPE</p><div>{n.partners.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.text}</p><strong>{item.focus}</strong></article>)}</div></section>}
<section id="read-the-land" className="study-analysis"><div className="authored-section-head"><p className="eyebrow">02 / READ THE LAND</p><h2>{n.analysisTitle}</h2><p>{n.analysisIntro}</p></div><Tabs defaultValue="0" className="narrative-tabs"><TabsList aria-label="Site analysis layers" className="narrative-tab-list">{n.layers.map((l,i)=><TabsTrigger key={l.title} value={String(i)}>{l.title}</TabsTrigger>)}</TabsList>{n.layers.map((l,i)=><TabsContent key={l.title} value={String(i)} className="analysis-panel"><button className={`analysis-art ${n.key==='sandplan'&&l.title==='Everyday use'?'circulation-drawing':n.key==='sandplan'&&l.title==='Habitat'?'habitat-photo':n.key==='bells-pond'?'vegetation-drawing':''}`} onClick={()=>picture(l.image,n.key==='sandplan'&&l.title==='Habitat'?'Nearby sandplain habitat':n.key==='bells-pond'?(bellsAnalysisTitles[l.title]||l.title):l.title)}>{n.key==='bells-pond'&&l.title==='Vegetation'&&<div className="plan-brand-header">Vegetation Analysis Drawn By Anna Goff, CSLD '26</div>}<img src={watermarkedPlan(l.image)} alt={l.alt} loading="lazy"/><span>{n.key==='sandplan'&&l.title==='Habitat'?'NEARBY SANDPLAIN HABITAT ↗':'ENLARGE DRAWING ↗'}</span></button><div className="analysis-copy">{n.key==='bells-pond'&&bellsAnalysisTitles[l.title]&&<p className="analysis-author-title">{bellsAnalysisTitles[l.title]}</p>}<p className="eyebrow">{l.label}</p><h3>{l.headline}</h3><p>{l.text}</p><div className="design-implication"><span>DESIGN RESPONSE</span><p>{l.response}</p></div></div></TabsContent>)}</Tabs></section>
<section id="design-choices" className="study-choices"><div className="authored-section-head"><p className="eyebrow">03 / DESIGN CHOICES</p><h2>{n.choicesTitle}</h2><p>{n.choicesIntro}</p></div><Tabs defaultValue="0" className="narrative-tabs"><TabsList aria-label="Design alternatives" className="narrative-tab-list">{n.choices.map((c,i)=><TabsTrigger key={c.title} value={String(i)}>{c.title}</TabsTrigger>)}</TabsList>{n.choices.map((c,i)=><TabsContent key={c.title} value={String(i)} className="choice-panel"><button className={n.key==='sandplan'?'branded-concept':undefined} onClick={()=>picture(c.image,c.title)}>{n.key==='sandplan'&&<div className="plan-brand-header">Sweetfern Ecological Design</div>}<img src={watermarkedPlan(c.image)} alt={c.title+' concept plan'} loading="lazy"/></button><div><span className="eyebrow">CONCEPT 0{i+1}</span><h3>{c.headline}</h3><p>{c.text}</p><ul>{c.points.map(t=><li key={t}>{t}</li>)}</ul><p className="choice-tradeoff"><strong>The balance</strong>{c.tradeoff}</p></div></TabsContent>)}</Tabs><p className="design-resolution"><strong>The final direction</strong>{n.resolution}</p></section>
<section id="explore-plan" className="study-plan"><div className="authored-section-head"><p className="eyebrow">04 / EXPLORE THE LANDSCAPE</p><h2>{n.planTitle}</h2><p>Select a place on the plan to explore its design.</p></div><div className="plan-explorer"><div><div className="hotspot-map"><img src={watermarkedPlan(n.plan)} alt={n.planAlt} loading="lazy"/>{n.features.map((f,i)=><button key={f.title} style={{left:f.x+'%',top:f.y+'%'}} className={feature===i?'active':''} aria-label={f.title} aria-pressed={feature===i} onClick={()=>setFeature(i)}>{String(i+1).padStart(2,'0')}</button>)}</div><button className="line-link" onClick={()=>picture(n.plan,n.planTitle)}>Open large plan ↗</button></div><div className="feature-reader"><div className="feature-index" role="group" aria-label="Landscape destinations">{n.features.map((f,i)=><button key={f.title} aria-pressed={feature===i} onClick={()=>setFeature(i)}>{String(i+1).padStart(2,'0')} {f.title}</button>)}</div><article key={active.title} aria-live="polite"><p className="eyebrow">{active.category}</p><h3>{active.title}</h3><p>{active.text}</p><ul>{active.points.map(t=><li key={t}>{t}</li>)}</ul></article></div></div></section>
<section id="living-landscape" className="study-living"><div className="authored-section-head"><p className="eyebrow">05 / {n.key==='sandplan'?'A LANDSCAPE FOR DAILY LIFE':'NEIGHBORHOOD & PUBLIC LAND'}</p><h2>{n.livingTitle}</h2></div>{n.scenes.map((s,i)=><article className="living-scene" key={s.title}><button onClick={()=>picture(s.image,s.title)}><img src={watermarkedPlan(s.image)} alt={s.alt} loading="lazy"/></button><div><p className="eyebrow">{s.label}</p><h3>{s.title}</h3><p>{s.text}</p><Accordion>{s.details.map((d,j)=><AccordionItem value={String(j)} key={d.title}><AccordionTrigger>{d.title}</AccordionTrigger><AccordionContent><p>{d.text}</p></AccordionContent></AccordionItem>)}</Accordion></div></article>)}</section>
<section id="planting-communities" className="study-plants"><div className="authored-section-head"><p className="eyebrow">06 / PLANT COMMUNITIES</p><h2>{n.plantTitle}</h2><p>{n.plantIntro}</p></div><div className="community-stories">{n.communities.map((c,i)=><article key={c.title}>{<figure className="community-reference"><button onClick={()=>picture(`/studies/${n.key}/${communityImages[i][0]}.webp`,communityImages[i][1])} aria-label={`Enlarge ${c.title} planting reference`}><img src={watermarkedPlan(`/studies/${n.key}/${communityImages[i][0]}.webp`)} alt={communityImages[i][1]} loading="lazy"/><b aria-hidden="true">↗</b></button><figcaption>{n.key==='sandplan'?'Planting reference':'Landscape reference'} · {c.title}</figcaption></figure>}<h3>{c.title}</h3>{<details className="community-notes"><summary>Explore this planting ↗</summary><p>{c.text}</p><p>{c.care}</p></details>}</article>)}</div><details className="plant-palette-drawer" ><summary>Explore the planting palette <span>Plant names, growing conditions & seasonal detail</span></summary><p className="palette-key">Planting positions and dimensions describe the project palette. Mesic means moderately moist soil.</p><div className="plant-tools"><label>Find a plant<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Common name, botanical name, or role"/></label><div role="group" aria-label="Plant community">{['All',...new Set(n.plants.map(x=>x.community))].map(c=><button key={c} aria-pressed={community===c} onClick={()=>setCommunity(c)}>{c}</button>)}</div></div><p className="plant-result" aria-live="polite">{plants.length} palette {plants.length===1?'entry':'entries'}</p><div className="native-plant-grid">{plants.slice(0,shown).map(x=><article key={x.latin+x.community}><span>{x.community}</span><h3>{x.name}</h3><i>{x.latin}</i><p>{x.role}</p><dl><div><dt>POSITION</dt><dd>{x.light}</dd></div><div><dt>SOIL</dt><dd>{x.soil}</dd></div>{x.height&&<div><dt>HEIGHT</dt><dd>{(x.height.includes("'")||x.height.includes('"')?x.height.replaceAll('"',' in').replaceAll("'",' ft'):x.height+' ft')}</dd></div>}{x.bloom&&<div><dt>BLOOM</dt><dd>{x.bloom}</dd></div>}</dl></article>)}</div>{plants.length>shown&&<button className="plant-more" onClick={()=>setShown(shown+12)}>Show 12 more plants ↓ <span>{shown} of {plants.length}</span></button>}{!plants.length&&<p>No plants match this search. Try another name or choose All.</p>}</details></section>
{n.neighbors&&<section className="good-neighbor"><div><p className="eyebrow">THE GOOD NEIGHBOR GARDEN</p><h2>Every garden belongs<br/>to a larger landscape.</h2><p>Our planting guide connects choices around the home with the health of nearby woods, meadows, and waterways. Select plants suited to local conditions, support a diversity of native species, and watch for garden plants spreading into the conservation land.</p></div><Accordion>{n.neighbors.map(item=><AccordionItem key={item.from} value={item.from}><AccordionTrigger>{item.from}<span>Explore an alternative +</span></AccordionTrigger><AccordionContent><h3>{item.to}</h3><p>{item.why}</p></AccordionContent></AccordionItem>)}</Accordion></section>}
<section id="long-term-care" className="study-care"><div className="authored-section-head"><p className="eyebrow">07 / STEWARDSHIP</p><h2>{n.careTitle}</h2><p>{n.careIntro}</p></div><div className="care-sequence">{n.care.map((c,i)=><article key={c.title}><span>0{i+1}</span><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
<section className="study-colophon"><p>{p.credit}</p><p>{n.colophon}</p><button className="line-link" aria-expanded={archive} onClick={()=>setArchive(!archive)}>{archive?'Close':'Open'} original plan set {archive?'−':'+'}</button></section>
{archive&&<section className="authored-archive"><h2>Original drawings & references.</h2><p>{details.source?.credit}</p><div className="document-grid">{details.documents.map(doc=><button className="document-card" key={doc.page} onClick={()=>picture(`${details.source?.directory}/page-${doc.page}.jpg`,doc.title)}><div className="document-preview"><img src={watermarkedPlan(`${details.source?.directory}/page-${doc.page}-thumb.webp`)} alt={doc.title} loading="lazy"/></div><div className="document-caption"><p className="eyebrow">{doc.type} / {doc.page}</p><h3>{doc.title}</h3></div></button>)}</div></section>}
<Dialog open={!!zoom} onOpenChange={open=>{if(!open)setZoom(null)}}><DialogContent className="art-dialog" showCloseButton={false}><button className="art-close" onClick={()=>setZoom(null)} aria-label="Close illustration">Close ×</button><DialogTitle>{zoom?.title}</DialogTitle><DialogDescription>Enlarge the drawing, then scroll across the plan to explore its details.</DialogDescription>{zoom&&<><div className="art-zoom-controls" role="group" aria-label="Drawing zoom"><button onClick={()=>setZoomLevel(v=>Math.max(100,v-25))} disabled={zoomLevel===100} aria-label="Zoom out">−</button><label htmlFor="art-zoom">Zoom <output>{zoomLevel}%</output></label><input id="art-zoom" type="range" min="100" max="300" step="25" value={zoomLevel} onChange={e=>setZoomLevel(Number(e.target.value))}/><button onClick={()=>setZoomLevel(v=>Math.min(300,v+25))} disabled={zoomLevel===300} aria-label="Zoom in">+</button><button onClick={()=>setZoomLevel(100)}>Fit</button></div><div className="art-zoom-viewport">{n.key==='bells-pond'&&n.layers.some(l=>l.title==='Vegetation'&&l.image===zoom.src)&&<div className="plan-brand-header">Vegetation Analysis Drawn By Anna Goff, CSLD '26</div>}{n.key==='sandplan'&&n.choices.some(c=>c.image===zoom.src)&&<div className="plan-brand-header">Sweetfern Ecological Design</div>}<img style={{width:`${zoomLevel}%`,maxWidth:'none',maxHeight:'none'}} src={watermarkedPlan(zoom.src)} alt={zoom.title}/></div><a className="art-full-image" href={watermarkedPlan(zoom.src)} target="_blank" rel="noreferrer">Open full-size image ↗</a></>}</DialogContent></Dialog>
</div>}
