
import {watermarkedPlan} from "@/lib/plan-watermarks";
import {projects} from '@/lib/projects';
const contexts:Record<string,{title:string;intro:string;slugs:string[]}>= {
 'site-analysis':{title:'From site evidence to design.',intro:'Two Conway School studies show how soils, water, vegetation, and patterns of use inform decisions at very different scales.',slugs:['sandplan-meadow-and-landscape','bells-pond']},
 'site-planning':{title:'Locate the parts. Consider the whole.',intro:'Compare the household scale of Sandplain Meadow Oasis with the shared conservation and housing landscape at Bell’s Pond.',slugs:['bells-pond','sandplan-meadow-and-landscape']},
 'meadows':{title:'Different ground. Different meadows.',intro:'The Sandplain Meadow Oasis proposal, Bell’s Pond’s habitat mosaic, and the photographed Tyringham landscape offer distinct perspectives on meadow design and care.',slugs:['sandplan-meadow-and-landscape','bells-pond']},
 'gardens-and-planting':{title:'Planting as a connected system.',intro:'From rain gardens and productive beds to native planting around a pocket neighborhood, these studies connect the garden to its wider ecology.',slugs:['sandplan-meadow-and-landscape','bells-pond']},
 'ecological-restoration':{title:'Restoration across scales.',intro:'The Bell’s Pond study links woodland recovery, meadow and shrubland management, and residential planting within one conservation framework.',slugs:['bells-pond']},
 'management':{title:'Many missions. Shared ground.',intro:'The Bell’s Pond school study responds to the shared and organization-specific goals of a land conservancy, Habitat for Humanity, and a community land trust. It offers a planning example of how public access, private homes, and ecological priorities can be considered together.',slugs:['bells-pond']},
 'stewardship':{title:'Care is part of the design.',intro:'Explore habitat management by vegetation zone at Bell’s Pond and the dry-site planting communities at Sandplain Meadow Oasis. Both studies connect design intent with the care a landscape will need.',slugs:['bells-pond','sandplan-meadow-and-landscape']},
 'design':{title:'Read the land. Reveal the possibilities.',intro:'Residential design and conservation planning, documented through original analysis, drawings, and planting palettes.',slugs:['sandplan-meadow-and-landscape','bells-pond']}
};
export default function StudyConnections({context}:{context:string}){const c=contexts[context];if(!c)return null;return <section className="study-connections"><div className="section-title"><div><p className="eyebrow">ANALYSIS IN PRACTICE / DESIGN STUDIES</p><h2>{c.title}</h2></div><p>{c.intro}</p></div><div className="study-connection-grid">{c.slugs.map(slug=>{const p=projects.find(x=>x.slug===slug)!;return <a href={watermarkedPlan(`/projects/${slug}#details`)} key={slug}><p className="card-school-header">{slug==='sandplan-meadow-and-landscape'?'Conway School of Landscape Design':'Conway School of Landscape Design: Co-designed with Anna Goff'}</p><div className={`study-card-image card-photo card-drawing ${slug==='sandplan-meadow-and-landscape'?'card-sandplan':slug==='bells-pond'?'card-bells':''}`}><img src={slug==='bells-pond'?'/watermarked-plans/bells-pond-card-plan.svg':watermarkedPlan(p.hero)} alt={p.title+' — proposed landscape illustration'} loading="lazy"/>{slug==='sandplan-meadow-and-landscape'&&<div className="card-map-title"><strong>Residence - Plan Render</strong><span>Drawn by Zaviere Drumm CSLD &apos;26</span></div>}<span className="card-school-logo"><img src="/images/conway-school-logo.svg" alt="The Conway School of Landscape Design"/></span><span className="study-card-action">EXPLORE THE PROJECT ↗</span></div><p className="eyebrow">{p.category}</p><h3>{p.title}</h3><p>{p.summary}</p><small>{p.credit}</small></a>})}</div><a className="line-link" href={watermarkedPlan("/landscape-design/conservation-and-housing")}>Conservation + housing planning ↗</a></section>}
