'use client';
import {watermarkedPlan} from "@/lib/plan-watermarks";

import {useState,useEffect} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import type {Project} from '@/lib/projects';
import type {ProjectDetails} from '@/lib/project-details';
import type {StudyNarrative} from '@/lib/study-narratives';
const bellsAnalysisTitles:Record<string,string>={Vegetation:'Vegetation Analysis by Anna Goff',Soils:'Soil Analysis by Zaviere Drumm','Water + slopes':'Hydrology Analysis by Anna Goff','Habitat + access':'Vegetation Analysis by Anna Goff'};
const sandplanDetailViews=["340 460 630 540","440 850 560 420","800 650 460 480","1050 920 430 430","1300 1070 410 380","1510 1050 400 390","1080 1260 300 310"];
const sandplanCommunityImages=[['rain-garden-reference','Iris flowering at the water’s edge'],['entry-reference','Layered coneflowers and perennial planting'],['front-meadow-reference-clean','Flowering coneflowers in a meadow planting'],['screen-reference','Evergreen foliage for a planted screen'],['south-yard-reference','Pine canopy and open understory'],['sandplain-reference','Montague Sandplain, a nearby analogous habitat with the same soil conditions']];
const bellsCommunityImages=[['meadow-reference','Flowering asters in a meadow'],['shrubland-reference','Sumac fruit and layered foliage'],['upland-reference','Maple canopy in autumn'],['before-creek','Existing creekside vegetation at Bell’s Pond'],['neighborhood','Residential planting and shared greenspace design illustration']];
export default function StudyExperience({project:p,details,narrative:n}:{project:Project;details:ProjectDetails;narrative:StudyNarrative}){
const[zoomLevel,setZoomLevel]=useState(100);const[shown,setShown]=useState(12);const[feature,setFeature]=useState(0);const[community,setCommunity]=useState('All');const[query,setQuery]=useState('');const[zoom,setZoom]=useState<{src:string;title:string}|null>(null);const[archive,setArchive]=useState(false);
useEffect(()=>{const hash=location.hash;if(hash==='#photographs'||hash==='#details')requestAnimationFrame(()=>document.getElementById(hash==='#details'?'read-the-land':'explore-plan')?.scrollIntoView({behavior:'instant'}));},[]);
useEffect(()=>setShown(12),[query,community]);
const communityImages=n.key==='sandplan'?sandplanCommunityImages:bellsCommunityImages;const active=n.features[feature];const plants=n.plants.filter(x=>(n.key==='sandplan'||community==='All'||x.community===community)&&`${x.name} ${x.latin} ${x.role}`.toLowerCase().replaceAll(/\s/g,'').includes(query.toLowerCase().replaceAll(/\s/g,'')));
const picture=(src:string,title:string)=>{setZoomLevel(100);setZoom({src,title});};
return <div className={`authored-study ${n.key}`}>
<section className="authored-lead"><div><a className="eyebrow" href={watermarkedPlan("/projects")}>← ALL PROJECTS</a><p className="eyebrow study-kicker">{n.kicker}</p><h1>{n.title}</h1><p className="authored-deck">{n.subtitle}</p><a className="line-link" href={watermarkedPlan("#explore-plan")}>Explore the landscape ↓</a></div><div className="lead-art"><img src={n.key==='sandplan'?'/watermarked-plans/sandplain-illustration-paperless.svg':watermarkedPlan(n.hero)} alt={n.heroAlt}/></div></section>
<div className="authored-byline"><span>{p.location}</span><span>{p.credit?.split(' · ').slice(0,-1).join(' · ')}</span><span>{n.date} · Landscape design</span></div>
<nav className="study-chapter-nav" aria-label="Project chapters">{[['The brief','the-brief'],['Site analysis','read-the-land'],['Design choices','design-choices'],['Explore the plan','explore-plan'],[n.key==='sandplan'?'Living outdoors':'Neighborhood + trails','living-landscape'],['Planting','planting-communities'],['Stewardship','long-term-care']].map(([label,id],i)=><a key={id} href={watermarkedPlan('#'+id)}><span>0{i+1}</span>{label}</a>)}</nav>
<section id="the-brief" className="authored-intro"><div><p className="eyebrow">01 / THE BRIEF</p><h2>{n.briefTitle}</h2></div><div>{n.brief.map(t=><p key={t}>{t}</p>)}<ul className="authored-tags">{p.tags.map(t=><li key={t}>{t}</li>)}</ul></div><dl className="study-metrics">{n.metrics.map(m=><div key={m.label}><dt>{m.value}</dt><dd>{m.label}</dd></div>)}</dl></section><div className="study-photo-strip">{(n.key==='sandplan'?[['before-house','Existing home — single-level living and a home to age in place.'],['before-garden','The existing vegetable garden'],['before-meadow','Meadow beginnings']]:[['before-creek','Creekside vegetation'],['before-field','An existing route through the site'],['renovated-barn','The renovated barn']]).map(([file,caption])=><figure key={file}><img src={watermarkedPlan(`/studies/${n.key}/${file}.webp`)} alt={caption} loading="lazy"/><figcaption>{caption}</figcaption></figure>)}</div>
{n.partners&&<section className="study-partners"><p className="eyebrow">THREE MISSIONS / ONE LANDSCAPE</p><div>{n.partners.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.text}</p><strong>{item.focus}</strong></article>)}</div></section>}
<section id="read-the-land" className="study-analysis"><div className="authored-section-head"><p className="eyebrow">02 / READ THE LAND</p><h2>{n.analysisTitle}</h2><p>{n.analysisIntro}</p></div><Tabs defaultValue="0" className="narrative-tabs"><TabsList aria-label="Site analysis layers" className="narrative-tab-list">{n.layers.map((l,i)=><TabsTrigger key={l.title} value={String(i)}>{l.title}</TabsTrigger>)}</TabsList>{n.layers.map((l,i)=><TabsContent key={l.title} value={String(i)} className="analysis-panel"><div className={`analysis-art ${n.key==='sandplan'&&l.title==='Sun + shade'?'sun-shade-drawing':n.key==='sandplan'&&l.title==='Everyday use'?'circulation-drawing':n.key==='sandplan'&&l.title==='Habitat'?'habitat-photo':n.key==='bells-pond'?'vegetation-drawing':''}`}>{n.key==='bells-pond'&&l.title==='Vegetation'&&<div className="plan-brand-header">Vegetation Analysis Drawn By Anna Goff, CSLD '26</div>}{n.key==='sandplan'&&l.title==='Soil + water'&&<div className="plan-brand-header">Soil Analysis</div>}<img src={watermarkedPlan(l.image)} alt={l.alt} loading="lazy"/></div><div className="analysis-copy">{n.key==='bells-pond'&&bellsAnalysisTitles[l.title]&&<p className="analysis-author-title">{bellsAnalysisTitles[l.title]}</p>}<p className="eyebrow">{l.label}</p><h3>{l.headline}</h3><p>{l.text}</p><div className="design-implication"><span>DESIGN RESPONSE</span><p>{l.response}</p></div></div></TabsContent>)}</Tabs></section>
<section id="design-choices" className="study-choices"><div className="authored-section-head"><p className="eyebrow">03 / DESIGN CHOICES</p><h2>{n.choicesTitle}</h2><p>{n.choicesIntro}</p></div><Tabs defaultValue="0" className="narrative-tabs"><TabsList aria-label="Design alternatives" className="narrative-tab-list">{n.choices.map((c,i)=><TabsTrigger key={c.title} value={String(i)}>{c.title}</TabsTrigger>)}</TabsList>{n.choices.map((c,i)=><TabsContent key={c.title} value={String(i)} className="choice-panel"><div className={n.key==='sandplan'?'branded-concept':undefined}>{n.key==='sandplan'&&<div className="plan-brand-header">Sweetfern Ecological Design</div>}<img src={watermarkedPlan(c.image)} alt={c.title+' concept plan'} loading="lazy"/></div><div><span className="eyebrow">CONCEPT 0{i+1}</span><h3>{c.headline}</h3><p>{c.text}</p><ul>{c.points.map(t=><li key={t}>{t}</li>)}</ul><p className="choice-tradeoff"><strong>The balance</strong>{c.tradeoff}</p></div></TabsContent>)}</Tabs><p className="design-resolution"><strong>The final direction</strong>{n.resolution}</p></section>
<section id="explore-plan" className="study-plan"><div className="authored-section-head"><p className="eyebrow">04 / EXPLORE THE LANDSCAPE</p><h2>{n.planTitle}</h2><p>Select a place on the plan to explore its design.</p></div><div className="plan-explorer"><div>{n.key==='sandplan'&&<div className="plan-brand-header">Sandplain Meadow Oasis · Landscape Plan <small>Southampton, Massachusetts · Sweetfern Ecological Design</small></div>}<div className="hotspot-map">{n.key==='sandplan'?<svg className="framed-plan" viewBox="220 450 1770 1000" role="img" aria-label={n.planAlt}><image href={watermarkedPlan(n.plan)} width="2149" height="2000" transform="rotate(-35 1074.5 1000)"/><g transform="translate(1710 1320)" fill="#213a2b"><rect x="-35" y="-45" width="240" height="150" fill="#f5f4ed"/><text x="0" y="-12" fontSize="20">Approx. scale · feet</text><rect width="49" height="9"/><rect x="49" width="49" height="9" fill="white" stroke="#213a2b"/><text y="36" fontSize="18">0</text><text x="43" y="36" fontSize="18">10</text><text x="91" y="36" fontSize="18">20</text></g></svg>:<img src={watermarkedPlan(n.plan)} alt={n.planAlt} loading="lazy"/>}{n.features.map((f,i)=><button key={f.title} style={{left:(n.key==='sandplan'?((f.x*21.49-1074.5)*0.819152+(f.y*20-1000)*0.573576+1074.5-220)/17.7:f.x)+'%',top:(n.key==='sandplan'?(-(f.x*21.49-1074.5)*0.573576+(f.y*20-1000)*0.819152+1000-450)/10:f.y)+'%'}} className={feature===i?'active':''} aria-label={f.title} aria-pressed={feature===i} onClick={()=>setFeature(i)}>{String(i+1).padStart(2,'0')}</button>)}</div></div><div className="feature-reader"><div className="destination-media"><div className="feature-index" role="group" aria-label="Landscape destinations">{n.features.map((f,i)=><button key={f.title} aria-pressed={feature===i} onClick={()=>setFeature(i)}>{String(i+1).padStart(2,'0')} {f.title}</button>)}</div>{n.key==='sandplan'&&<figure className="destination-detail">{feature===6?<img src="/studies/sandplan/play-spiral-enhanced.webp" alt="Elevated play spiral — enhanced plan detail"/>:<svg viewBox={sandplanDetailViews[feature]} role="img" aria-label={active.title+' — detail from the landscape plan'}><defs><clipPath id="destination-paper-edge"><path d={feature===1?'M440 850H1000V1270H900L835 1245 750 1215 680 1170 610 1145 540 1110 485 1060 440 1000Z':feature===5?'M1510 1050H1750L1800 1095 1875 1150 1850 1220 1800 1260 1770 1320 1710 1355 1660 1440H1510Z':'M0 0H2149V2000H0Z'}/></clipPath></defs><image href={watermarkedPlan(n.plan)} width="2149" height="2000" clipPath="url(#destination-paper-edge)"/></svg>}<figcaption>{active.title} · Plan detail</figcaption></figure>}</div><article key={active.title} aria-live="polite"><p className="eyebrow">{active.category}</p><h3>{active.title}</h3><p>{active.text}</p><ul>{active.points.map(t=><li key={t}>{t}</li>)}</ul></article></div></div></section>
<section id="living-landscape" className="study-living"><div className="authored-section-head"><p className="eyebrow">05 / {n.key==='sandplan'?'A LANDSCAPE FOR DAILY LIFE':'NEIGHBORHOOD & PUBLIC LAND'}</p><h2>{n.livingTitle}</h2></div>{n.scenes.map((s,i)=><article className="living-scene" key={s.title}><div className="living-art"><img src={watermarkedPlan(s.image)} alt={s.alt} loading="lazy"/></div><div><p className="eyebrow">{s.label}</p><h3>{s.title}</h3><p>{s.text}</p><Accordion>{s.details.map((d,j)=><AccordionItem value={String(j)} key={d.title}><AccordionTrigger>{d.title}</AccordionTrigger><AccordionContent><p>{d.text}</p></AccordionContent></AccordionItem>)}</Accordion></div></article>)}</section>
<section id="planting-communities" className="study-plants"><div className="authored-section-head"><p className="eyebrow">06 / PLANT COMMUNITIES</p><h2>{n.plantTitle}</h2><p>{n.plantIntro}</p></div><div className="community-stories">{n.communities.map((c,i)=><article key={c.title}>{<figure className="community-reference"><button onClick={()=>picture(`/studies/${n.key}/${communityImages[i][0]}.webp`,communityImages[i][1])} aria-label={`Enlarge ${c.title} planting reference`}><img src={watermarkedPlan(`/studies/${n.key}/${communityImages[i][0]}.webp`)} alt={communityImages[i][1]} loading="lazy"/><b aria-hidden="true">↗</b></button><figcaption>{n.key==='sandplan'&&c.title==='Sandplain meadow'?'Montague Sandplain · A nearby analogous habitat with the same soil conditions':(n.key==='sandplan'?'Planting reference':'Landscape reference')+' · '+c.title}</figcaption></figure>}<h3>{c.title}</h3>{<details className="community-notes"><summary>Explore this planting ↗</summary><p>{c.text}</p><p>{c.care}</p></details>}</article>)}</div></section>
{n.neighbors&&<section className="good-neighbor"><div><p className="eyebrow">THE GOOD NEIGHBOR GARDEN</p><h2>Every garden belongs<br/>to a larger landscape.</h2><p>Our planting guide connects choices around the home with the health of nearby woods, meadows, and waterways. Select plants suited to local conditions, support a diversity of native species, and watch for garden plants spreading into the conservation land.</p></div><Accordion>{n.neighbors.map(item=><AccordionItem key={item.from} value={item.from}><AccordionTrigger>{item.from}<span>Explore an alternative +</span></AccordionTrigger><AccordionContent><h3>{item.to}</h3><p>{item.why}</p></AccordionContent></AccordionItem>)}</Accordion></section>}
<section id="long-term-care" className="study-care"><div className="authored-section-head"><p className="eyebrow">07 / STEWARDSHIP</p><h2>{n.careTitle}</h2><p>{n.careIntro}</p></div><div className="care-sequence">{n.care.map((c,i)=><article key={c.title}><span>0{i+1}</span><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
<section className="study-colophon"><p>{p.credit}</p><p>{n.colophon}</p><button className="line-link" aria-expanded={archive} onClick={()=>setArchive(!archive)}>{archive?'Close':'Open'} original plan set {archive?'−':'+'}</button></section>
{archive&&<section className="authored-archive"><h2>Original drawings & references.</h2><p>{details.source?.credit}</p><div className="document-grid">{details.documents.map(doc=><div className="document-card" key={doc.page}><div className="document-preview"><img src={watermarkedPlan(`${details.source?.directory}/page-${doc.page}-thumb.webp`)} alt={doc.title} loading="lazy"/></div><div className="document-caption"><p className="eyebrow">{doc.type} / {doc.page}</p><h3>{doc.title}</h3></div></div>)}</div></section>}
<Dialog open={!!zoom} onOpenChange={open=>{if(!open)setZoom(null)}}><DialogContent className="art-dialog" showCloseButton={false}><button className="art-close" onClick={()=>setZoom(null)} aria-label="Close illustration">Close ×</button><DialogTitle>{zoom?.title}</DialogTitle><DialogDescription>Enlarge the drawing, then scroll across the plan to explore its details.</DialogDescription>{zoom&&<><div className="art-zoom-controls" role="group" aria-label="Drawing zoom"><button onClick={()=>setZoomLevel(v=>Math.max(100,v-25))} disabled={zoomLevel===100} aria-label="Zoom out">−</button><label htmlFor="art-zoom">Zoom <output>{zoomLevel}%</output></label><input id="art-zoom" type="range" min="100" max="300" step="25" value={zoomLevel} onChange={e=>setZoomLevel(Number(e.target.value))}/><button onClick={()=>setZoomLevel(v=>Math.min(300,v+25))} disabled={zoomLevel===300} aria-label="Zoom in">+</button><button onClick={()=>setZoomLevel(100)}>Fit</button></div><div className="art-zoom-viewport">{n.key==='bells-pond'&&n.layers.some(l=>l.title==='Vegetation'&&l.image===zoom.src)&&<div className="plan-brand-header">Vegetation Analysis Drawn By Anna Goff, CSLD '26</div>}{n.key==='sandplan'&&n.choices.some(c=>c.image===zoom.src)&&<div className="plan-brand-header">Sweetfern Ecological Design</div>}<img style={{width:`${zoomLevel}%`,maxWidth:'none',maxHeight:'none'}} src={watermarkedPlan(zoom.src)} alt={zoom.title}/></div><a className="art-full-image" href={watermarkedPlan(zoom.src)} target="_blank" rel="noreferrer">Open full-size image ↗</a></>}</DialogContent></Dialog>
</div>}
