import {Header,Footer} from '@/components/shell';
import {watermarkedPlan} from '@/lib/plan-watermarks';
export default function TransitToTrailsProject(){return <main id="top"><Header/><section className="conservation-project-heading"><a className="eyebrow" href="/projects/">← ALL PROJECTS</a><p className="eyebrow">CONWAY SCHOOL OF LANDSCAPE DESIGN · COLLABORATIVE PROJECT · WINTER 2026</p><h1>Berkshire County:<br/><em>Transit to Trails Regional Plan</em></h1><p>A mapping framework for equitable access to outdoor recreation across Berkshire County, Massachusetts.</p><p className="winter-project-credit">Natalie Wilks & Zaviere Drumm · Prepared for Berkshire Natural Resources Council</p></section><section id="details" className="winter-project-overview"><div><p className="eyebrow">REGIONAL PLANNING / GIS + ACCESS</p><h2>Conserved land is only<br/><em>part of the story.</em></h2><p>This countywide study examined how transportation, trailhead infrastructure, population patterns, and landscape conditions shape equitable access to outdoor recreation. GIS mapping, field observations, and regional planning data connected Environmental Justice communities, public transit, conserved land, ecological resources, and recreation destinations.</p><p>A proximity analysis and trail/gateway tier framework translated those conditions into opportunities for investment: transit-connected recreation, community gateways, trailhead improvements, walkability, wayfinding, and alternative transportation. Site-specific case studies tested how those regional priorities could work on the ground.</p></div><figure><a href={watermarkedPlan('/studies/transit-to-trails/regional-access.webp')} target="_blank" rel="noreferrer"><img src={watermarkedPlan('/studies/transit-to-trails/regional-access.webp')} alt="Berkshire County map of trails within half a mile of Environmental Justice communities"/><span className="line-link">Enlarge the regional analysis ↗</span></a><figcaption>Trail proximity to Environmental Justice communities · Collaborative GIS analysis</figcaption></figure></section><section className="winter-project-highlights"><p className="eyebrow">THREE DIRECTIONS FOR ACTION</p><div><article><h2>Connect existing routes.</h2><p>Build on places where trails and transit already overlap through better trailheads, wayfinding, and programmed access.</p></article><article><h2>Strengthen local access.</h2><p>Prioritize neighborhood connections, accessible infrastructure, and community stewardship close to where people live.</p></article><article><h2>Reach regional destinations.</h2><p>Explore service extensions and microtransit to connect population centers with important recreation landscapes.</p></article></div></section><section className="winter-project-case"><div className="winter-map-montage">{[
['clarksburg-access','Clarksburg · Trail access and transit'],
['regional-access','Berkshire County · Trails and Environmental Justice communities'],
['kennedy-access','Kennedy Park · Community and trailhead connections']
].map(([file,label])=><figure key={file}><a href={watermarkedPlan('/studies/transit-to-trails/'+file+'.webp')} target="_blank" rel="noreferrer"><img src={watermarkedPlan('/studies/transit-to-trails/'+file+'.webp')} alt={label} loading="lazy"/><span>View larger ↗</span></a><figcaption>{label}</figcaption></figure>)}</div><div><p className="eyebrow">BNRC’S GOALS / OUR APPROACH</p><h2>Connect communities<br/><em>with conserved land.</em></h2><p>Berkshire Natural Resources Council commissioned this study to improve equitable access to conserved lands, particularly for people without reliable transportation. The goal was to identify stronger connections between communities, public transit, and trailheads—and guide future conservation and recreation planning. Access to nature was treated as infrastructure supporting public health, climate resilience, environmental justice, and regional stewardship.</p><p>Our team combined GIS mapping, regional planning data, and field observations to study access, connectivity, and the visitor experience. We mapped transit routes, trailheads, population patterns, and Environmental Justice communities, then used local case studies and sketches to translate those findings into design opportunities.</p><div className="bells-project-links"><a className="line-link" href="https://issuu.com/conwaydesign/docs/transit_for_trails_mapping_equitable_access_to_ou" target="_blank" rel="noreferrer">Read the full plan on Issuu ↗</a><a className="line-link" href="/projects/">Explore more projects ↗</a></div></div></section><section className="winter-sketches"><p className="eyebrow">CASE-STUDY SKETCHES / DRAWN BY ZAVIERE DRUMM</p><h2>Picture the journey.</h2><p>Sketches explore how arrival, wayfinding, rest areas, and sensitive trail connections can make a trip from town to trail more welcoming.</p><div>{[
['clarksburg-arrival','Clarksburg · Arrival from transit','A bus stop and clear trailhead connection welcome visitors into the forest.'],
['clarksburg-gathering','Clarksburg · A place to gather','A shaded rest area makes room to pause and spend time beside the stream.'],
['kennedy-arrival','Kennedy Park · Connecting town and trail','A proposed arrival point brings transit closer to the park entrance.'],
['kennedy-boardwalk','Kennedy Park · Learning through the landscape','A boardwalk and overlook guide exploration through sensitive ecological areas.']
].map(([file,title,text])=><figure key={file}><a href={watermarkedPlan('/studies/transit-to-trails/'+file+'.webp')} target="_blank" rel="noreferrer"><img src={watermarkedPlan('/studies/transit-to-trails/'+file+'.webp')} alt={text} loading="lazy"/></a><figcaption><h3>{title}</h3><p>{text}</p><p>Drawn by Zaviere Drumm · Concept sketch</p></figcaption></figure>)}</div></section><Footer/></main>}
