import {studyDetails} from './plan-studies';
export type DetailChapter={title:string;subtitle:string;body:string;image:string;alt:string;page:number;points:string[]};
export type ProjectDetails={title:string;intro:string;scope:string;status:string;source?:{directory:string;title:string;credit:string;note:string};pages:number[];chapters:DetailChapter[];palette:{name:string;role:string;note:string}[];documents:{page:number;title:string;type:string;description:string}[]};
export const projectDetails:Record<string,ProjectDetails>={...studyDetails,
'137-summer':{
title:'One landscape.\nMany connected parts.',intro:'Read the landscape through the Tyringham portfolio: arrival, circulation, productive planting, and the spaces in between. The original sheets show the design decisions behind the photographed gardens.',scope:'Entry · paths · edible garden · driveway',status:'Built-work photographs and design studies',pages:[8,9,10,11,18],
chapters:[
{title:'A considered arrival',subtitle:'01 / MAIN ENTRY',body:'The formal approach connects the driveway to the porch and breezeway. Natural stone and reclaimed granite establish the route, while planting fills the spaces around the masonry.',image:'/images/summer-21.webp',alt:'The house and planted stone approach',page:8,points:['Native grasses and groundcovers fill open beds as a living green mulch.','Trailing ornamentals are used at walls; smaller ornamental trees are selected to coexist with drystack retaining walls.','The perspective study explores plank pavers, oversized natural granite, and rebuilt stone walls.']},
{title:'Paths that belong to the slope',subtitle:'02 / CIRCULATION & CRAFT',body:'A series of hardscape solutions gives access to different parts of the site. The portfolio emphasizes reclaimed granite and hand-selected natural stone, including many pieces found on site.',image:'/images/summer-24.webp',alt:'Natural stone steps fitted into a planted slope',page:10,points:['Stone steps resolve transitions between levels.','Paved passages connect the house and outdoor destinations.','The material language continues across formal entry, garden paths, and terrace edges.']},
{title:'Landscape edging',subtitle:'STONE + PLANTING',body:'Natural stone defines the path through the garden, while planting softens its edges and connects the route to the surrounding landscape.',image:'/images/summer-100.webp',alt:'Stone path and planted edges leading toward the treehouse',page:10,points:['Stone steppers establish a route through the planting.','Low planting meets the path along its edges.']},
{title:'A productive place to pause',subtitle:'03 / BERRY PATCH & GRAPE PERGOLA',body:'A steep planting bed is renovated as a destination garden and a shady refuge from the open lawn. Berries and native plants attractive to pollinators bring food production into the ornamental landscape.',image:'/images/summer-32.webp',alt:'Flowering plants in the summer garden',page:11,points:['The portfolio records blueberries, blackberries, alpine strawberries, grapes, chokeberries, cornelian cherries, juneberries, and raspberries.','A grape pergola creates an overhead element within the garden.','Natural stone steps connect the planted slope to the surrounding lawn.']},
{title:'The working edge of arrival',subtitle:'04 / DRIVEWAY & DRAINAGE',body:'The driveway sheet brings planting and water movement into the same plan. Its annotations identify drainage pitches, a road swale, drystack retaining walls, and naturalistic screen planting.',image:'/images/summer-160.webp',alt:'Aerial view of the house and surrounding paths',page:18,points:['The original drawing records cobble surfaces and directional drainage notes.','Screen planting follows the long edge of the driveway.','The sheet is dated October 20, 2024; annotations describe the drawing, not a verified as-built survey.']}
],palette:[{name:'Reclaimed granite',role:'Steps & paving',note:'Used with selected natural stone to connect the entry and garden paths.'},{name:'Natural stone',role:'Walls & transitions',note:'Drystack masonry, oversized paving, and pieces selected from the site.'},{name:'Grasses & groundcovers',role:'Living ground layer',note:'Native planting fills open beds around the formal entry.'},{name:'Berries & vines',role:'Edible destination garden',note:'Eight fruit groups are named in the berry patch and pergola description.'}],documents:[{page:9,title:'Main entry: sketch & stonework',type:'PERSPECTIVE STUDY',description:'Planting options, hardscape spacing, and a photograph of the constructed entry.'},{page:18,title:'Driveway hardscape & planting',type:'WORKING PLAN',description:'Original grading, drainage, material, and planting annotations.'},{page:10,title:'Stairs & paths',type:'MATERIAL STUDY',description:'Photographic examples of access solutions in granite and natural stone.'},{page:11,title:'Berry patch & grape pergola',type:'PLANTING STUDY',description:'Planting intent, edible palette, and garden photographs.'}]},
'pool-terrace':{
title:'A framework of stone.\nSoftened by planting.',intro:'A closer look at the pool terrace’s hardscape, garden connections, and gathering spaces, with the working plan and construction photograph from the Tyringham portfolio.',scope:'Pool terrace · fire features · steppers',status:'Working plan and built-work photographs',pages:[3,4,5,6,7],chapters:[
{title:'Reclaimed granite as the foundation',subtitle:'01 / HARDSCAPE',body:'The pool installation uses reclaimed granite to establish the terrace. The working plan records the pool, planting beds, surrounding paving, and the transition to the pool house.',image:'/images/summer-84.webp',alt:'Reclaimed stone around a planted pool terrace',page:4,points:['An overhead construction photograph sits above the working hardscape plan.','The plan distinguishes planting beds, lawn, and paved gathering areas.','Dimensions and levels are retained in the original sheet for close inspection.']},
{title:'Spaces for gathering',subtitle:'02 / OUTDOOR ROOMS',body:'A wood fire pit area and gas fire trough feature create two distinct destinations. Their relationship to the pool and planting is documented in the hardscape plan.',image:'/images/summer-81.webp',alt:'Planted outdoor gathering area beside the pool',page:3,points:['The plan marks a gas fire feature beside the pool.','A separate fire pit area is shown, with final location noted as pending on the drawing.','The pool-house landing and outdoor shower are also annotated on the sheet.']},
{title:'A planted seam between spaces',subtitle:'03 / PLANTING & MOVEMENT',body:'Patio and stepping-stone routes move through lawn and garden beds. Primarily native plants and groundcovers make the stone terrace part of a more naturalistic garden.',image:'/images/summer-38.webp',alt:'Planting frames stone paving at the pool',page:3,points:['Steppers extend circulation beyond the continuous terrace.','Groundcovers occupy the garden’s lower layer.','Planting beds connect the pool edge with the surrounding slope.']}
],palette:[{name:'Reclaimed granite',role:'Pool hardscape',note:'The primary terrace material described in the portfolio.'},{name:'Stone steppers',role:'Garden circulation',note:'Routes pass through lawn and planted beds.'},{name:'Native plants',role:'Garden structure',note:'The described palette is primarily native; no complete species schedule is supplied.'},{name:'Groundcovers',role:'Lower planting layer',note:'Part of the naturalistic planting around the hardscape.'}],documents:[{page:4,title:'Pool terrace: working hardscape plan',type:'PLAN & CONSTRUCTION',description:'Overhead construction photography and the original annotated plan, dated October 10, 2022.'},{page:3,title:'Pool hardscape & planting brief',type:'DESIGN BRIEF',description:'The documented material palette, gathering features, and planting approach.'}]},
'meadow-and-paths':{
title:'A change in management.\nA richer landscape.',intro:'The Sloped Upper Meadow brief describes converting a heavily mown former farm pasture into a diverse meadow, with connected paths, orchards, and food plantings.',scope:'Meadow conversion · footpaths · orchards',status:'Design intent and meadow reclamation photographs',pages:[2,10],chapters:[
{title:'Work with a difficult slope',subtitle:'01 / EXISTING CONDITIONS',body:'The starting point is a steep, historically farmed pasture maintained by frequent mowing. The design aims to establish a more diverse meadow landscape while keeping the space usable.',image:'/images/meadow-reclamation/meadow-mosaic.webp',alt:'Flowering meadow and connected paths across the slope',page:2,points:['The source identifies both steep terrain and frequent mowing as the starting conditions.','The objective is to create destinations within the slope.','The meadow is connected to the rest of the property rather than treated as an isolated area.']},
{title:'A path system through the planting',subtitle:'02 / ACCESS & DESTINATIONS',body:'Footpaths create a route through the meadow and link different parts of the property. The design brief describes the walk itself as an aesthetic experience.',image:'/images/meadow-reclamation/path-to-swing.webp',alt:'Stone steppers through the meadow leading to a timber swing',page:2,points:['Paths provide a way to move across and experience the site.','Destinations are positioned within the challenging terrain.','The separate Stairs and Paths sheet documents natural-stone access solutions used in the broader landscape.']},
{title:'Cultivate seasonal abundance',subtitle:'03 / ECOLOGY & STEWARDSHIP',body:'The proposed shift to a seasonal mowing pattern supports the meadow’s wildlife value. Multiple orchards and food plantings add benefits for the people who use the site and for wildlife.',image:'/images/meadow-reclamation/wildflowers.webp',alt:'White and yellow flowers among meadow grasses',page:2,points:['Reduce mowing from the previous heavily mown condition.','Introduce a seasonal pattern of maintenance.','Integrate orchard and food plantings; the meadow brief does not specify a complete species list or mowing calendar.']}
],palette:[{name:'Meadow vegetation',role:'Pasture conversion',note:'A more diverse planting landscape is the stated objective.'},{name:'Orchards',role:'Food & destinations',note:'Multiple orchards are included in the design intent.'},{name:'Food plantings',role:'People & wildlife',note:'A productive layer complements meadow habitat.'},{name:'Seasonal mowing',role:'Landscape management',note:'A changed maintenance pattern is integral to the project.'}],documents:[{page:2,title:'Sloped Upper Meadow',type:'DESIGN BRIEF',description:'Existing conditions, meadow objectives, footpath strategy, and portfolio photographs.'},{page:10,title:'Stairs & paths in the landscape',type:'RELATED MATERIAL STUDY',description:'Reclaimed granite and hand-selected stone access solutions from the wider Tyringham work.'}]},
'pond-restoration':{
title:'Rebuild the edge.\nRestore the relationship.',intro:'The pond brief connects bank stabilization, native planting, wildlife habitat, and outdoor use. The portfolio records this work as in progress.',scope:'Pond banks · planting terraces · stonework',status:'In progress in the source portfolio',pages:[12],chapters:[
{title:'Respond to an eroding edge',subtitle:'01 / EXISTING CONDITIONS',body:'The restoration addresses an eroding bank and a failing drystack wall. Regrading creates room for a different edge condition, combining planting terraces with boulders.',image:'/images/pond-0.webp',alt:'Pond edge during planting and restoration work',page:12,points:['The source identifies erosion and failing masonry as the existing problems.','Banks are regraded to incorporate planting terraces.','Boulders become part of the new bank structure.']},
{title:'Build habitat into the bank',subtitle:'02 / ECOLOGICAL STRUCTURE',body:'Boulder retention is introduced with habitat for fish and amphibians in mind. Native planting and seeding occupy areas previously affected by the failing wall and eroding bank.',image:'/images/pond-7.webp',alt:'Native planting work along the pond',page:12,points:['Plant and seed multiple native species along the restored edge.','Use native plants identified for erosion control.','Combine boulders and planted terraces to create a more varied habitat edge.']},
{title:'Reconnect people with the water',subtitle:'03 / ACCESS & GATHERING',body:'The wider brief includes a natural-stone patio, fire pit, beach, paths, and walkways. These elements make places to approach and enjoy the pond alongside the ecological restoration.',image:'/images/summer-107.webp',alt:'A place to sit beside the pond in the summer garden',page:12,points:['A natural-stone patio and fire pit form gathering destinations.','A beach and path network provide different experiences of the water’s edge.','The portfolio does not confirm completion of every listed element.']}
],palette:[{name:'Boulders',role:'Bank structure & habitat',note:'Retention work is designed with fish and amphibians in mind.'},{name:'Native plants & seed',role:'Revegetation',note:'Used where erosion and failing masonry affected the bank.'},{name:'Planting terraces',role:'Regraded pond edge',note:'Terraces combine plants and boulders along the bank.'},{name:'Natural stone',role:'Patio & paths',note:'Part of the documented gathering and access scope.'}],documents:[{page:12,title:'Pond restoration & hardscaping',type:'IN-PROGRESS RECORD',description:'The original project brief and photographs of bank work, planting, and stonework.'}]}
};
